conda-forge/jupyterlite-core-feedstock

- .scripts/build_steps.sh
- .scripts/logging_utils.sh
- recipe/meta.yaml
> Update to `0.2.0a1`

- recipe/meta.yaml
> jupyterlite-core 0.2.0a3

- recipe/meta.yaml
> jupyterlite-core 0.2.0a4

- .ci_support/linux_64_.yaml
- .scripts/build_steps.sh
- recipe/conda_build_config.yaml
- recipe/meta.yaml
> Jupyterlite-core 0.2.0b0

- README.md
- recipe/meta.yaml
> Jupyterlite-core 0.2.0b1 (remove mathjax)

- .ci_support/linux_64_.yaml
- recipe/conda_build_config.yaml
- recipe/meta.yaml
> Jupyterlite-core 0.2.0rc0

- recipe/meta.yaml
> jupyterlite-core 0.2.0rc1

- .scripts/build_steps.sh
- README.md
- recipe/meta.yaml
> jupyterlite-core 0.2.0

- .scripts/build_steps.sh
- README.md
- build-locally.py
- recipe/meta.yaml
> Bump to `0.3.0a1`

- .azure-pipelines/azure-pipelines-linux.yml
- .gitignore
- .scripts/build_steps.sh
- .scripts/run_docker_build.sh
- README.md
- build-locally.py
- recipe/meta.yaml
> jupyterlite-core 0.3.0b0

- .azure-pipelines/azure-pipelines-linux.yml
- .gitignore
- .scripts/build_steps.sh
- .scripts/run_docker_build.sh
- README.md
- build-locally.py
- recipe/meta.yaml
> jupyterlite-core 0.3.0rc0

- .azure-pipelines/azure-pipelines-linux.yml
- .scripts/build_steps.sh
- recipe/meta.yaml
> jupyterlite-core 0.3.0rc1

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_64_.yaml
- .scripts/build_steps.sh
- README.md
- build-locally.py
- recipe/extract-third-party-licenses.py
- recipe/meta.yaml
> jupyterlite-core 0.3.0

- .ci_support/linux_64_.yaml
- .scripts/build_steps.sh
- azure-pipelines.yml
- recipe/meta.yaml
> jupyterlite-core 0.4.4

- recipe/meta.yaml
> jupyterlite-core 0.5.0a1

- recipe/meta.yaml
> jupyterlite-core 0.5.0a2

- .ci_support/linux_64_.yaml
- recipe/conda_build_config.yaml
- recipe/meta.yaml
Checklist
References:
- alternative to #46 (but keeps using `v0` recipe with `conda-build`)
> jupyterlite-core 0.6.0a0

- .gitignore
- recipe/meta.yaml
> Update to 0.5.1

- .ci_support/linux_64_.yaml
- recipe/conda_build_config.yaml
- recipe/meta.yaml
> jupyterlite-core 0.6.0a2

- .gitignore
- recipe/meta.yaml
> jupyterlite-core 0.6.0a3

- .ci_support/linux_64_.yaml
- recipe/conda_build_config.yaml
- recipe/meta.yaml
> jupyterlite-core 0.6.0a6

- .ci_support/linux_64_.yaml
- .scripts/run_docker_build.sh
- build-locally.py
- recipe/conda_build_config.yaml
- recipe/meta.yaml
> jupyterlite-core 0.6.0a8

- recipe/meta.yaml
> jupyterlite-core 0.6.0a9

- recipe/recipe.yaml
> jupyterlite-core 0.6.0b1

- recipe/recipe.yaml
> jupyterlite-core 0.7.0a2

- recipe/recipe.yaml
> jupyterlite-core 0.7.0a3

- recipe/recipe.yaml
> jupyterlite-core 0.7.0a4

- pixi.toml
- recipe/recipe.yaml
> jupyterlite-core 0.7.0a6
